<a href="https://colab.research.google.com/github/miriam-silva/testesp2icoma/blob/main/prova_02_miriam_silva.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Prova 01:** IBM | Direção Diária:
**Aluna:** Miriam Silva Corrêa

# Pipeline 1 | Extração de Dados [Fase 1]

## Bibliotecas

In [137]:
import requests
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, precision_score, recall_score, f1_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV

## Consumo da API (Alpha Vantage)

In [138]:
API_KEY = 'XBWDB57V8PK8DW8W'
symbol = 'IBM'
url = f'https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=IBM&apikey={API_KEY}&outputsize=compact'
response = requests.get(url)
data = response.json()

## Transformação para DataFrame

In [139]:
if 'Time Series (Daily)' in data:
  df = pd.DataFrame.from_dict(data['Time Series (Daily)'], orient='index')
  df.columns = ['open', 'high', 'low', 'close', 'volume']
  df = df.astype(float)
  df.index = pd.to_datetime(df.index)
  df = df.sort_index()
  print("Dados carregados com sucesso!")
else:
  print("Erro na API:", data)

Dados carregados com sucesso!

In [140]:
df.head()

              open     high       low   close      volume
2026-01-26  293.16  296.815  293.1400  296.33   3726890.0
2026-01-27  297.16  297.330  293.2700  293.86   2944722.0
2026-01-28  294.17  295.950  291.2601  294.16   5790347.0
2026-01-29  317.86  319.900  303.4700  309.24  10124929.0
2026-01-30  307.60  307.783  299.7300  306.70   5940669.0

# Pipeline 2 | Laborização (Feature Engineering) [Fase 2]

## Criação da Variável Alvo (Y)

In [141]:
df['target'] = (df['close'] > df['open']).astype(int)

## Criação de Preditores (X) baseados em Lags

In [142]:
df['variation'] = (df['close'] - df['open']) / df['open']
df['prev_variation'] = df['variation'].shift(1)
df['prev_variation_2'] = df['variation'].shift(2)
df['prev_variation_3'] = df['variation'].shift(3)
df['volume_log'] = np.log1p(df['volume'])

df['prev_volume'] = df['volume_log'].shift(1)
df['prev_volume_2'] = df['volume_log'].shift(2)

df_final = df[['prev_variation', 'prev_variation_2', 'prev_variation_3', 'prev_volume', 'prev_volume_2', 'target']].dropna()

print("Colunas extras removidas e valores nulos excluídos.")
df_final.head()

Colunas extras removidas e valores nulos excluídos.

,prev_variation,prev_variation_2,prev_variation_3,prev_volume,prev_volume_2,target
2026-01-29,-0.000034,-0.011105,0.010813,15.571703,14.895525,0
2026-01-30,-0.027119,-0.000034,-0.011105,16.130511,15.571703,0
2026-02-02,-0.002926,-0.027119,-0.000034,15.597332,16.130511,1
2026-02-03,0.023479,-0.002926,-0.027119,15.337469,15.597332,0
2026-02-04,-0.057907,0.023479,-0.002926,16.239961,15.337469,0

# Pipeline 3 | Tratamento e Normalização [Fase 3]

In [143]:
df_final.head()

,prev_variation,prev_variation_2,prev_variation_3,prev_volume,prev_volume_2,target
2026-01-29,-0.000034,-0.011105,0.010813,15.571703,14.895525,0
2026-01-30,-0.027119,-0.000034,-0.011105,16.130511,15.571703,0
2026-02-02,-0.002926,-0.027119,-0.000034,15.597332,16.130511,1
2026-02-03,0.023479,-0.002926,-0.027119,15.337469,15.597332,0
2026-02-04,-0.057907,0.023479,-0.002926,16.239961,15.337469,0

## Verificação de valores nulos

In [144]:
df_final.isnull().sum()

prev_variation      0
prev_variation_2    0
prev_variation_3    0
prev_volume         0
prev_volume_2       0
target              0
dtype: int64

## Estatísticas descritivas

In [145]:
df_final.describe()

,prev_variation,prev_variation_2,prev_variation_3,prev_volume,prev_volume_2,target
count,97.000000,97.000000,97.000000,97.000000,97.000000,97.000000
mean,-0.001980,-0.002092,-0.001856,15.697479,15.692192,0.474227
std,0.025717,0.025733,0.025745,0.499245,0.505020,0.501929
min,-0.121948,-0.121948,-0.121948,14.672507,14.672507,0.000000
25%,-0.012082,-0.012082,-0.011105,15.387766,15.378166,0.000000
50%,-0.001019,-0.002313,-0.001019,15.585256,15.585256,0.000000
75%,0.009595,0.009595,0.010526,15.939114,15.939114,1.000000
max,0.087669,0.087669,0.087669,17.308381,17.308381,1.000000

## Remoção de Outliers

In [146]:
df_final = df_final[
    (np.abs(df_final['prev_variation']) < 3 * df_final['prev_variation'].std()) &
    (np.abs(df_final['prev_variation_2']) < 3 * df_final['prev_variation_2'].std()) &
    (np.abs(df_final['prev_variation_3']) < 3 * df_final['prev_variation_3'].std())
]

## Seleção de Variáveis (X e y)

In [147]:
X = df_final[['prev_variation', 'prev_variation_2', 'prev_variation_3', 'prev_volume', 'prev_volume_2']]
y = df_final['target']

## Análise de Balanceamento das Classes

In [148]:
print(y.value_counts())

target
0    49
1    42
Name: count, dtype: int64

## Divisão Treino/Teste

In [149]:
tamanho = int(len(X)*0.9)

X_train = X[:tamanho]
X_test = X[tamanho:]

y_train = y[:tamanho]
y_test = y[tamanho:]

## Normalização (StandardScaler)

In [150]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Pipeline 4 | Decision Tree [Fase 4]

In [151]:
arvore_ibm = DecisionTreeClassifier(criterion='entropy', random_state=0)
arvore_ibm.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [152]:
previsoes_arvore = arvore_ibm.predict(X_test)

In [153]:
previsoes_arvore

array([1, 0, 0, 0, 1, 0, 0, 1, 1, 0])

In [154]:
accuracy_score(y_test, previsoes_arvore)

0.5

In [155]:
confusion_matrix(y_test, previsoes_arvore)

array([[5, 4],
       [1, 0]])

In [156]:
print(classification_report(y_test, previsoes_arvore))

              precision    recall  f1-score   support

           0       0.83      0.56      0.67         9
           1       0.00      0.00      0.00         1

    accuracy                           0.50        10
   macro avg       0.42      0.28      0.33        10
weighted avg       0.75      0.50      0.60        10

# Pipeline 5 | Modelagem por Random Forest [Fase 5]

In [157]:
random_ibm = RandomForestClassifier(n_estimators=10, criterion='entropy', random_state=0)
random_ibm.fit(X_train, y_train)
random_ibm

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [158]:
previsoes_random = random_ibm.predict(X_test)

In [159]:
previsoes_random

array([1, 0, 1, 0, 1, 1, 0, 1, 0, 1])

In [160]:
accuracy_score(y_test, previsoes_random)

0.5

In [161]:
confusion_matrix(y_test, previsoes_random)

array([[4, 5],
       [0, 1]])

In [162]:
print(classification_report(y_test, previsoes_random))

              precision    recall  f1-score   support

           0       1.00      0.44      0.62         9
           1       0.17      1.00      0.29         1

    accuracy                           0.50        10
   macro avg       0.58      0.72      0.45        10
weighted avg       0.92      0.50      0.58        10

# Pipeline 6 | SVM [Fase 6]

In [163]:
svm_ibm = SVC(kernel='rbf', C=2.0, random_state=1)
svm_ibm.fit(X_train, y_train)
svm_ibm

SVC(C=2.0, random_state=1)

In [164]:
svm_previsoes = svm_ibm.predict(X_test)
svm_previsoes

array([0, 1, 1, 1, 1, 1, 1, 1, 0, 1])

In [165]:
accuracy_score(y_test, svm_previsoes)

0.3

In [166]:
confusion_matrix(y_test, svm_previsoes)

array([[2, 7],
       [0, 1]])

In [167]:
print(classification_report(y_test, svm_previsoes))

              precision    recall  f1-score   support

           0       1.00      0.22      0.36         9
           1       0.12      1.00      0.22         1

    accuracy                           0.30        10
   macro avg       0.56      0.61      0.29        10
weighted avg       0.91      0.30      0.35        10

# Pipeline 7 | Redes Neurais [Fase 7 - IBM Base]

In [168]:
redeneural_ibm = MLPClassifier(verbose=True, max_iter=1000, tol=0.000010, solver='adam', hidden_layer_sizes=(100), activation='relu')
redeneural_ibm.fit(X_train, y_train)
redeneural_ibm

Iteration 1, loss = 0.69950496
Iteration 2, loss = 0.69624822
Iteration 3, loss = 0.69310755
Iteration 4, loss = 0.69006793
Iteration 5, loss = 0.68711028
Iteration 6, loss = 0.68425477
Iteration 7, loss = 0.68149231
Iteration 8, loss = 0.67880787
Iteration 9, loss = 0.67620423
Iteration 10, loss = 0.67369081
Iteration 11, loss = 0.67126459
Iteration 12, loss = 0.66892572
Iteration 13, loss = 0.66666990
Iteration 14, loss = 0.66449135
Iteration 15, loss = 0.66238297
Iteration 16, loss = 0.66034701
Iteration 17, loss = 0.65838169
Iteration 18, loss = 0.65649978
Iteration 19, loss = 0.65467292
Iteration 20, loss = 0.65290514
Iteration 21, loss = 0.65119600
Iteration 22, loss = 0.64953078
Iteration 23, loss = 0.64791679
Iteration 24, loss = 0.64634978
Iteration 25, loss = 0.64481898
Iteration 26, loss = 0.64332658
Iteration 27, loss = 0.64188064
Iteration 28, loss = 0.64047359
Iteration 29, loss = 0.63909802
Iteration 30, loss = 0.63774765
Iteration 31, loss = 0.63642512
Iteration 32, loss = 0.63512009
Iteration 33, loss = 0.63383547
Iteration 34, loss = 0.63257525
Iteration 35, loss = 0.63132873
Iteration 36, loss = 0.63009680
Iteration 37, loss = 0.62887932
Iteration 38, loss = 0.62767203
Iteration 39, loss = 0.62648330
Iteration 40, loss = 0.62531478
Iteration 41, loss = 0.62416183
Iteration 42, loss = 0.62301509
Iteration 43, loss = 0.62187199
Iteration 44, loss = 0.62073606
Iteration 45, loss = 0.61960517
Iteration 46, loss = 0.61848387
Iteration 47, loss = 0.61737487
Iteration 48, loss = 0.61628577
Iteration 49, loss = 0.61520031
Iteration 50, loss = 0.61412109
Iteration 51, loss = 0.61305214
Iteration 52, loss = 0.61199164
Iteration 53, loss = 0.61093452
Iteration 54, loss = 0.60988060
Iteration 55, loss = 0.60881877
Iteration 56, loss = 0.60775733
Iteration 57, loss = 0.60669435
Iteration 58, loss = 0.60562587
Iteration 59, loss = 0.60455949
Iteration 60, loss = 0.60347658
Iteration 61, loss = 0.60239311
Iteration 62, loss = 0.60132985
Iteration 63, loss = 0.60027451
Iteration 64, loss = 0.59922766
Iteration 65, loss = 0.59818625
Iteration 66, loss = 0.59715073
Iteration 67, loss = 0.59612216
Iteration 68, loss = 0.59510651
Iteration 69, loss = 0.59409409
Iteration 70, loss = 0.59308201
Iteration 71, loss = 0.59206726
Iteration 72, loss = 0.59104009
Iteration 73, loss = 0.59000680
Iteration 74, loss = 0.58896907
Iteration 75, loss = 0.58794013
Iteration 76, loss = 0.58691346
Iteration 77, loss = 0.58588909
Iteration 78, loss = 0.58486070
Iteration 79, loss = 0.58383331
Iteration 80, loss = 0.58281773
Iteration 81, loss = 0.58180768
Iteration 82, loss = 0.58079681
Iteration 83, loss = 0.57979273
Iteration 84, loss = 0.57879649
Iteration 85, loss = 0.57781878
Iteration 86, loss = 0.57684904
Iteration 87, loss = 0.57588749
Iteration 88, loss = 0.57494053
Iteration 89, loss = 0.57399932
Iteration 90, loss = 0.57305800
Iteration 91, loss = 0.57212367
Iteration 92, loss = 0.57120006
Iteration 93, loss = 0.57027297
Iteration 94, loss = 0.56934160
Iteration 95, loss = 0.56841669
Iteration 96, loss = 0.56749270
Iteration 97, loss = 0.56657721
Iteration 98, loss = 0.56568510
Iteration 99, loss = 0.56481194
Iteration 100, loss = 0.56395279
Iteration 101, loss = 0.56309959
Iteration 102, loss = 0.56225967
Iteration 103, loss = 0.56141774
Iteration 104, loss = 0.56057539
Iteration 105, loss = 0.55973757
Iteration 106, loss = 0.55890692
Iteration 107, loss = 0.55808027
Iteration 108, loss = 0.55725445
Iteration 109, loss = 0.55642226
Iteration 110, loss = 0.55559485
Iteration 111, loss = 0.55476795
Iteration 112, loss = 0.55394056
Iteration 113, loss = 0.55311780
Iteration 114, loss = 0.55229971
Iteration 115, loss = 0.55148691
Iteration 116, loss = 0.55067144
Iteration 117, loss = 0.54986037
Iteration 118, loss = 0.54906239
Iteration 119, loss = 0.54826215
Iteration 120, loss = 0.54746705
Iteration 121, loss = 0.54667568
Iteration 122, loss = 0.54588419
Iteration 123, loss = 0.54508737
Iteration 124, loss = 0.54428550
Iteration 125, loss = 0.54348846
Iteration 126, loss = 0.54269883
Iteration 127, loss = 0.54189848
Iteration 128, loss = 0.54109067
Iteration 129, loss = 0.54029237
Iteration 130, loss = 0.53949695
Iteration 131, loss = 0.53871407
Iteration 132, loss = 0.53793798
Iteration 133, loss = 0.53717021
Iteration 134, loss = 0.53640160
Iteration 135, loss = 0.53563043
Iteration 136, loss = 0.53485700
Iteration 137, loss = 0.53408821
Iteration 138, loss = 0.53332456
Iteration 139, loss = 0.53256643
Iteration 140, loss = 0.53180993
Iteration 141, loss = 0.53106345
Iteration 142, loss = 0.53032379
Iteration 143, loss = 0.52958919
Iteration 144, loss = 0.52885702
Iteration 145, loss = 0.52812660
Iteration 146, loss = 0.52739771
Iteration 147, loss = 0.52668077
Iteration 148, loss = 0.52597007
Iteration 149, loss = 0.52526267
Iteration 150, loss = 0.52455470
Iteration 151, loss = 0.52384976
Iteration 152, loss = 0.52315411
Iteration 153, loss = 0.52246014
Iteration 154, loss = 0.52176438
Iteration 155, loss = 0.52106668
Iteration 156, loss = 0.52037625
Iteration 157, loss = 0.51968944
Iteration 158, loss = 0.51900857
Iteration 159, loss = 0.51832653
Iteration 160, loss = 0.51764693
Iteration 161, loss = 0.51696837
Iteration 162, loss = 0.51629170
Iteration 163, loss = 0.51561005
Iteration 164, loss = 0.51493794
Iteration 165, loss = 0.51426889
Iteration 166, loss = 0.51360649
Iteration 167, loss = 0.51293833
Iteration 168, loss = 0.51226764
Iteration 169, loss = 0.51159966
Iteration 170, loss = 0.51093655
Iteration 171, loss = 0.51027855
Iteration 172, loss = 0.50962532
Iteration 173, loss = 0.50897048
Iteration 174, loss = 0.50830993
Iteration 175, loss = 0.50764754
Iteration 176, loss = 0.50699090
Iteration 177, loss = 0.50633192
Iteration 178, loss = 0.50568211
Iteration 179, loss = 0.50503736
Iteration 180, loss = 0.50440066
Iteration 181, loss = 0.50375723
Iteration 182, loss = 0.50312551
Iteration 183, loss = 0.50249352
Iteration 184, loss = 0.50185707
Iteration 185, loss = 0.50122311
Iteration 186, loss = 0.50058230
Iteration 187, loss = 0.49994212
Iteration 188, loss = 0.49930931
Iteration 189, loss = 0.49867924
Iteration 190, loss = 0.49804389
Iteration 191, loss = 0.49741224
Iteration 192, loss = 0.49678408
Iteration 193, loss = 0.49616897
Iteration 194, loss = 0.49555402
Iteration 195, loss = 0.49494147
Iteration 196, loss = 0.49432308
Iteration 197, loss = 0.49371284
Iteration 198, loss = 0.49311233
Iteration 199, loss = 0.49251270
Iteration 200, loss = 0.49191700
Iteration 201, loss = 0.49132068
Iteration 202, loss = 0.49072340
Iteration 203, loss = 0.49013345
Iteration 204, loss = 0.48954550
Iteration 205, loss = 0.48895316
Iteration 206, loss = 0.48837581
Iteration 207, loss = 0.48780928
Iteration 208, loss = 0.48724115
Iteration 209, loss = 0.48667537
Iteration 210, loss = 0.48610823
Iteration 211, loss = 0.48553763
Iteration 212, loss = 0.48496808
Iteration 213, loss = 0.48438657
Iteration 214, loss = 0.48380732
Iteration 215, loss = 0.48322701
Iteration 216, loss = 0.48264091
Iteration 217, loss = 0.48205641
Iteration 218, loss = 0.48146482
Iteration 219, loss = 0.48086958
Iteration 220, loss = 0.48028237
Iteration 221, loss = 0.47968636
Iteration 222, loss = 0.47909295
Iteration 223, loss = 0.47850041
Iteration 224, loss = 0.47791551
Iteration 225, loss = 0.47732645
Iteration 226, loss = 0.47673010
Iteration 227, loss = 0.47612874
Iteration 228, loss = 0.47553245
Iteration 229, loss = 0.47494464
Iteration 230, loss = 0.47436227
Iteration 231, loss = 0.47377553
Iteration 232, loss = 0.47318575
Iteration 233, loss = 0.47259468
Iteration 234, loss = 0.47200280
Iteration 235, loss = 0.47141734
Iteration 236, loss = 0.47082597
Iteration 237, loss = 0.47024636
Iteration 238, loss = 0.46966633
Iteration 239, loss = 0.46908294
Iteration 240, loss = 0.46850862
Iteration 241, loss = 0.46793129
Iteration 242, loss = 0.46735177
Iteration 243, loss = 0.46677870
Iteration 244, loss = 0.46620584
Iteration 245, loss = 0.46562641
Iteration 246, loss = 0.46505090
Iteration 247, loss = 0.46447161
Iteration 248, loss = 0.46390333
Iteration 249, loss = 0.46332631
Iteration 250, loss = 0.46274516
Iteration 251, loss = 0.46216572
Iteration 252, loss = 0.46159041
Iteration 253, loss = 0.46101414
Iteration 254, loss = 0.46044050
Iteration 255, loss = 0.45987124
Iteration 256, loss = 0.45929862
Iteration 257, loss = 0.45871921
Iteration 258, loss = 0.45813883
Iteration 259, loss = 0.45756483
Iteration 260, loss = 0.45698593
Iteration 261, loss = 0.45641326
Iteration 262, loss = 0.45584356
Iteration 263, loss = 0.45527600
Iteration 264, loss = 0.45472594
Iteration 265, loss = 0.45417065
Iteration 266, loss = 0.45360374
Iteration 267, loss = 0.45304801
Iteration 268, loss = 0.45248907
Iteration 269, loss = 0.45193117
Iteration 270, loss = 0.45137410
Iteration 271, loss = 0.45081567
Iteration 272, loss = 0.45025250
Iteration 273, loss = 0.44968685
Iteration 274, loss = 0.44911858
Iteration 275, loss = 0.44855093
Iteration 276, loss = 0.44798302
Iteration 277, loss = 0.44741519
Iteration 278, loss = 0.44684174
Iteration 279, loss = 0.44626238
Iteration 280, loss = 0.44568400
Iteration 281, loss = 0.44510100
Iteration 282, loss = 0.44452594
Iteration 283, loss = 0.44395871
Iteration 284, loss = 0.44340179
Iteration 285, loss = 0.44283739
Iteration 286, loss = 0.44227561
Iteration 287, loss = 0.44170945
Iteration 288, loss = 0.44113905
Iteration 289, loss = 0.44057205
Iteration 290, loss = 0.44000871
Iteration 291, loss = 0.43944055
Iteration 292, loss = 0.43886861
Iteration 293, loss = 0.43829479
Iteration 294, loss = 0.43772128
Iteration 295, loss = 0.43715118
Iteration 296, loss = 0.43658650
Iteration 297, loss = 0.43601884
Iteration 298, loss = 0.43544678
Iteration 299, loss = 0.43488261
Iteration 300, loss = 0.43431543
Iteration 301, loss = 0.43375794
Iteration 302, loss = 0.43319497
Iteration 303, loss = 0.43263471
Iteration 304, loss = 0.43207324
Iteration 305, loss = 0.43151207
Iteration 306, loss = 0.43094789
Iteration 307, loss = 0.43038552
Iteration 308, loss = 0.42981869
Iteration 309, loss = 0.42924931
Iteration 310, loss = 0.42869804
Iteration 311, loss = 0.42814608
Iteration 312, loss = 0.42759688
Iteration 313, loss = 0.42704601
Iteration 314, loss = 0.42650034
Iteration 315, loss = 0.42594747
Iteration 316, loss = 0.42539327
Iteration 317, loss = 0.42483559
Iteration 318, loss = 0.42428453
Iteration 319, loss = 0.42374205
Iteration 320, loss = 0.42319317
Iteration 321, loss = 0.42265366
Iteration 322, loss = 0.42211068
Iteration 323, loss = 0.42157709
Iteration 324, loss = 0.42104514
Iteration 325, loss = 0.42052107
Iteration 326, loss = 0.41998709
Iteration 327, loss = 0.41945279
Iteration 328, loss = 0.41892496
Iteration 329, loss = 0.41840144
Iteration 330, loss = 0.41788239
Iteration 331, loss = 0.41736278
Iteration 332, loss = 0.41683632
Iteration 333, loss = 0.41632352
Iteration 334, loss = 0.41581146
Iteration 335, loss = 0.41530754
Iteration 336, loss = 0.41478941
Iteration 337, loss = 0.41427667
Iteration 338, loss = 0.41377260
Iteration 339, loss = 0.41326148
Iteration 340, loss = 0.41274073
Iteration 341, loss = 0.41223317
Iteration 342, loss = 0.41172500
Iteration 343, loss = 0.41120798
Iteration 344, loss = 0.41069640
Iteration 345, loss = 0.41018994
Iteration 346, loss = 0.40968021
Iteration 347, loss = 0.40917089
Iteration 348, loss = 0.40867640
Iteration 349, loss = 0.40817571
Iteration 350, loss = 0.40766696
Iteration 351, loss = 0.40715476
Iteration 352, loss = 0.40664384
Iteration 353, loss = 0.40614598
Iteration 354, loss = 0.40565061
Iteration 355, loss = 0.40514562
Iteration 356, loss = 0.40463380
Iteration 357, loss = 0.40412797
Iteration 358, loss = 0.40362646
Iteration 359, loss = 0.40312508
Iteration 360, loss = 0.40261839
Iteration 361, loss = 0.40211000
Iteration 362, loss = 0.40160110
Iteration 363, loss = 0.40110432
Iteration 364, loss = 0.40060587
Iteration 365, loss = 0.40010434
Iteration 366, loss = 0.39960543
Iteration 367, loss = 0.39910192
Iteration 368, loss = 0.39860674
Iteration 369, loss = 0.39811547
Iteration 370, loss = 0.39761843
Iteration 371, loss = 0.39712838
Iteration 372, loss = 0.39664378
Iteration 373, loss = 0.39615198
Iteration 374, loss = 0.39566531
Iteration 375, loss = 0.39517267
Iteration 376, loss = 0.39468209
Iteration 377, loss = 0.39418930
Iteration 378, loss = 0.39369243
Iteration 379, loss = 0.39320247
Iteration 380, loss = 0.39271296
Iteration 381, loss = 0.39223261
Iteration 382, loss = 0.39175581
Iteration 383, loss = 0.39127132
Iteration 384, loss = 0.39078280
Iteration 385, loss = 0.39028838
Iteration 386, loss = 0.38980362
Iteration 387, loss = 0.38932191
Iteration 388, loss = 0.38884472
Iteration 389, loss = 0.38835304
Iteration 390, loss = 0.38787456
Iteration 391, loss = 0.38739059
Iteration 392, loss = 0.38690424
Iteration 393, loss = 0.38642548
Iteration 394, loss = 0.38593680
Iteration 395, loss = 0.38546069
Iteration 396, loss = 0.38497923
Iteration 397, loss = 0.38450725
Iteration 398, loss = 0.38403661
Iteration 399, loss = 0.38356230
Iteration 400, loss = 0.38308572
Iteration 401, loss = 0.38261219
Iteration 402, loss = 0.38213252
Iteration 403, loss = 0.38165446
Iteration 404, loss = 0.38118005
Iteration 405, loss = 0.38069886
Iteration 406, loss = 0.38021482
Iteration 407, loss = 0.37974141
Iteration 408, loss = 0.37926427
Iteration 409, loss = 0.37878340
Iteration 410, loss = 0.37829982
Iteration 411, loss = 0.37781381
Iteration 412, loss = 0.37732674
Iteration 413, loss = 0.37684832
Iteration 414, loss = 0.37637451
Iteration 415, loss = 0.37589072
Iteration 416, loss = 0.37540588
Iteration 417, loss = 0.37492762
Iteration 418, loss = 0.37444821
Iteration 419, loss = 0.37396904
Iteration 420, loss = 0.37349829
Iteration 421, loss = 0.37300973
Iteration 422, loss = 0.37253342
Iteration 423, loss = 0.37205067
Iteration 424, loss = 0.37156741
Iteration 425, loss = 0.37107776
Iteration 426, loss = 0.37059627
Iteration 427, loss = 0.37011183
Iteration 428, loss = 0.36962149
Iteration 429, loss = 0.36912800
Iteration 430, loss = 0.36864177
Iteration 431, loss = 0.36814191
Iteration 432, loss = 0.36764047
Iteration 433, loss = 0.36714096
Iteration 434, loss = 0.36664691
Iteration 435, loss = 0.36615161
Iteration 436, loss = 0.36565017
Iteration 437, loss = 0.36515607
Iteration 438, loss = 0.36467490
Iteration 439, loss = 0.36419025
Iteration 440, loss = 0.36369512
Iteration 441, loss = 0.36321396
Iteration 442, loss = 0.36272559
Iteration 443, loss = 0.36223404
Iteration 444, loss = 0.36174753
Iteration 445, loss = 0.36125459
Iteration 446, loss = 0.36076418
Iteration 447, loss = 0.36027634
Iteration 448, loss = 0.35977825
Iteration 449, loss = 0.35929005
Iteration 450, loss = 0.35879349
Iteration 451, loss = 0.35829763
Iteration 452, loss = 0.35780955
Iteration 453, loss = 0.35731685
Iteration 454, loss = 0.35682396
Iteration 455, loss = 0.35634493
Iteration 456, loss = 0.35586235
Iteration 457, loss = 0.35536912
Iteration 458, loss = 0.35489241
Iteration 459, loss = 0.35441960
Iteration 460, loss = 0.35393603
Iteration 461, loss = 0.35346547
Iteration 462, loss = 0.35299187
Iteration 463, loss = 0.35252401
Iteration 464, loss = 0.35206501
Iteration 465, loss = 0.35157331
Iteration 466, loss = 0.35111073
Iteration 467, loss = 0.35064021
Iteration 468, loss = 0.35015228
Iteration 469, loss = 0.34967724
Iteration 470, loss = 0.34920258
Iteration 471, loss = 0.34871944
Iteration 472, loss = 0.34823079
Iteration 473, loss = 0.34775210
Iteration 474, loss = 0.34727855
Iteration 475, loss = 0.34679579
Iteration 476, loss = 0.34631063
Iteration 477, loss = 0.34582279
Iteration 478, loss = 0.34532660
Iteration 479, loss = 0.34484812
Iteration 480, loss = 0.34435060
Iteration 481, loss = 0.34385605
Iteration 482, loss = 0.34335549
Iteration 483, loss = 0.34285373
Iteration 484, loss = 0.34236419
Iteration 485, loss = 0.34186747
Iteration 486, loss = 0.34135603
Iteration 487, loss = 0.34085038
Iteration 488, loss = 0.34035266
Iteration 489, loss = 0.33985508
Iteration 490, loss = 0.33936054
Iteration 491, loss = 0.33886921
Iteration 492, loss = 0.33836607
Iteration 493, loss = 0.33788713
Iteration 494, loss = 0.33741149
Iteration 495, loss = 0.33692347
Iteration 496, loss = 0.33644765
Iteration 497, loss = 0.33594708
Iteration 498, loss = 0.33544569
Iteration 499, loss = 0.33495087
Iteration 500, loss = 0.33445822
Iteration 501, loss = 0.33394915
Iteration 502, loss = 0.33343691
Iteration 503, loss = 0.33292645
Iteration 504, loss = 0.33242492
Iteration 505, loss = 0.33191833
Iteration 506, loss = 0.33139354
Iteration 507, loss = 0.33086640
Iteration 508, loss = 0.33036025
Iteration 509, loss = 0.32985039
Iteration 510, loss = 0.32935595
Iteration 511, loss = 0.32885994
Iteration 512, loss = 0.32835418
Iteration 513, loss = 0.32783537
Iteration 514, loss = 0.32734187
Iteration 515, loss = 0.32684295
Iteration 516, loss = 0.32634845
Iteration 517, loss = 0.32588232
Iteration 518, loss = 0.32541330
Iteration 519, loss = 0.32494258
Iteration 520, loss = 0.32445954
Iteration 521, loss = 0.32398926
Iteration 522, loss = 0.32351466
Iteration 523, loss = 0.32304613
Iteration 524, loss = 0.32257097
Iteration 525, loss = 0.32209561
Iteration 526, loss = 0.32163361
Iteration 527, loss = 0.32116532
Iteration 528, loss = 0.32069694
Iteration 529, loss = 0.32021406
Iteration 530, loss = 0.31974244
Iteration 531, loss = 0.31930006
Iteration 532, loss = 0.31884347
Iteration 533, loss = 0.31838950
Iteration 534, loss = 0.31792927
Iteration 535, loss = 0.31746410
Iteration 536, loss = 0.31699480
Iteration 537, loss = 0.31652723
Iteration 538, loss = 0.31606582
Iteration 539, loss = 0.31560874
Iteration 540, loss = 0.31513913
Iteration 541, loss = 0.31466837
Iteration 542, loss = 0.31420887
Iteration 543, loss = 0.31374813
Iteration 544, loss = 0.31327792
Iteration 545, loss = 0.31280917
Iteration 546, loss = 0.31234836
Iteration 547, loss = 0.31188791
Iteration 548, loss = 0.31142347
Iteration 549, loss = 0.31096855
Iteration 550, loss = 0.31051070
Iteration 551, loss = 0.31004863
Iteration 552, loss = 0.30958745
Iteration 553, loss = 0.30913506
Iteration 554, loss = 0.30868057
Iteration 555, loss = 0.30822675
Iteration 556, loss = 0.30778600
Iteration 557, loss = 0.30733870
Iteration 558, loss = 0.30688444
Iteration 559, loss = 0.30643435
Iteration 560, loss = 0.30600251
Iteration 561, loss = 0.30556537
Iteration 562, loss = 0.30513069
Iteration 563, loss = 0.30468820
Iteration 564, loss = 0.30423658
Iteration 565, loss = 0.30378706
Iteration 566, loss = 0.30335177
Iteration 567, loss = 0.30291108
Iteration 568, loss = 0.30246583
Iteration 569, loss = 0.30202436
Iteration 570, loss = 0.30158287
Iteration 571, loss = 0.30114421
Iteration 572, loss = 0.30072104
Iteration 573, loss = 0.30028945
Iteration 574, loss = 0.29984960
Iteration 575, loss = 0.29941408
Iteration 576, loss = 0.29897501
Iteration 577, loss = 0.29854253
Iteration 578, loss = 0.29810937
Iteration 579, loss = 0.29766781
Iteration 580, loss = 0.29723422
Iteration 581, loss = 0.29680663
Iteration 582, loss = 0.29637709
Iteration 583, loss = 0.29594392
Iteration 584, loss = 0.29549460
Iteration 585, loss = 0.29506726
Iteration 586, loss = 0.29464491
Iteration 587, loss = 0.29420604
Iteration 588, loss = 0.29377909
Iteration 589, loss = 0.29335040
Iteration 590, loss = 0.29292315
Iteration 591, loss = 0.29248962
Iteration 592, loss = 0.29205564
Iteration 593, loss = 0.29162089
Iteration 594, loss = 0.29119941
Iteration 595, loss = 0.29077859
Iteration 596, loss = 0.29034634
Iteration 597, loss = 0.28992404
Iteration 598, loss = 0.28949295
Iteration 599, loss = 0.28906995
Iteration 600, loss = 0.28865365
Iteration 601, loss = 0.28823196
Iteration 602, loss = 0.28780843
Iteration 603, loss = 0.28738402
Iteration 604, loss = 0.28696449
Iteration 605, loss = 0.28654217
Iteration 606, loss = 0.28612212
Iteration 607, loss = 0.28570551
Iteration 608, loss = 0.28528471
Iteration 609, loss = 0.28487322

/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(

MLPClassifier(hidden_layer_sizes=100, max_iter=1000, tol=1e-05, verbose=True)

In [169]:
redeneural_ibm.out_activation_

'logistic'

In [170]:
previsoes_redeneural = redeneural_ibm.predict(X_test)
previsoes_redeneural

array([0, 0, 0, 0, 1, 1, 0, 0, 1, 1])

In [171]:
accuracy_score(y_test, previsoes_redeneural)

0.7

In [172]:
confusion_matrix(y_test, previsoes_redeneural)

array([[6, 3],
       [0, 1]])

In [173]:
print(classification_report(y_test, previsoes_redeneural))

              precision    recall  f1-score   support

           0       1.00      0.67      0.80         9
           1       0.25      1.00      0.40         1

    accuracy                           0.70        10
   macro avg       0.62      0.83      0.60        10
weighted avg       0.93      0.70      0.76        10

# Pipeline 8 | KNN [Fase 8 - IBM Base]

In [174]:
parametros = {'n_neighbors': [3, 5, 10, 20], 'p': [1, 2]}

In [175]:
grid_ibm = GridSearchCV(estimator=KNeighborsClassifier(), param_grid=parametros)
grid_ibm.fit(X_train, y_train)

GridSearchCV(estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': [3, 5, 10, 20], 'p': [1, 2]})

In [176]:
melhor_parametros_ibm = grid_ibm.best_params_
melhor_resultado_ibm = grid_ibm.best_score_

In [177]:
print(melhor_parametros_ibm)
print(melhor_resultado_ibm)

{'n_neighbors': 20, 'p': 1}
0.5426470588235295

In [178]:
knn_ibm = KNeighborsClassifier(n_neighbors=melhor_parametros_ibm['n_neighbors'], p=melhor_parametros_ibm['p'])
knn_ibm.fit(X_train, y_train)
knn_ibm

KNeighborsClassifier(n_neighbors=20, p=1)

In [179]:
previsoes_knn = knn_ibm.predict(X_test)

In [180]:
previsoes_knn

array([1, 0, 1, 1, 1, 1, 1, 0, 0, 1])

In [181]:
accuracy_score(y_test, previsoes_knn)

0.4

In [182]:
confusion_matrix(y_test, previsoes_knn)

array([[3, 6],
       [0, 1]])

In [183]:
confusion_matrix(y_test, previsoes_knn)

array([[3, 6],
       [0, 1]])

In [184]:
print(classification_report(y_test, previsoes_knn))

              precision    recall  f1-score   support

           0       1.00      0.33      0.50         9
           1       0.14      1.00      0.25         1

    accuracy                           0.40        10
   macro avg       0.57      0.67      0.38        10
weighted avg       0.91      0.40      0.47        10

# Pipeline 9 | Comparação dos modelos [Fase 9]

In [185]:
resultado_modelos = pd.DataFrame({
    'Modelo': ['Decision Tree', 'Random Forest', 'SVM', 'Redes Neurais', 'KNN'],
    'Acurácia': [
        accuracy_score(y_test, previsoes_arvore),
        accuracy_score(y_test, previsoes_random),
        accuracy_score(y_test, svm_previsoes),
        accuracy_score(y_test, previsoes_redeneural),
        accuracy_score(y_test, previsoes_knn)
    ]
})

resultado_modelos.sort_values(by='Acurácia', ascending=False)

          Modelo  Acurácia
3  Redes Neurais       0.7
0  Decision Tree       0.5
1  Random Forest       0.5
4            KNN       0.4
2            SVM       0.3