<a href="https://colab.research.google.com/github/miriam-silva/testesp2icoma/blob/main/prova_02_miriam_silva.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Prova 01:** IBM | Direção Diária:
**Aluna:** Miriam Silva Corrêa

# Pipeline 1 | Extração de Dados [Fase 1]

## Bibliotecas

In [ ]:
import requests
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, precision_score, recall_score, f1_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV

## Consumo da API (Alpha Vantage)

In [ ]:
API_KEY = 'XBWDB57V8PK8DW8W'
symbol = 'IBM'
url = f'https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=IBM&apikey={API_KEY}&outputsize=compact'
response = requests.get(url)
data = response.json()

## Transformação para DataFrame

In [ ]:
if 'Time Series (Daily)' in data:
  df = pd.DataFrame.from_dict(data['Time Series (Daily)'], orient='index')
  df.columns = ['open', 'high', 'low', 'close', 'volume']
  df = df.astype(float)
  df.index = pd.to_datetime(df.index)
  df = df.sort_index()
  print("Dados carregados com sucesso!")
else:
  print("Erro na API:", data)

Dados carregados com sucesso!

In [ ]:
df.head()

              open     high       low   close      volume
2026-01-26  293.16  296.815  293.1400  296.33   3726890.0
2026-01-27  297.16  297.330  293.2700  293.86   2944722.0
2026-01-28  294.17  295.950  291.2601  294.16   5790347.0
2026-01-29  317.86  319.900  303.4700  309.24  10124929.0
2026-01-30  307.60  307.783  299.7300  306.70   5940669.0

# Pipeline 2 | Laborização (Feature Engineering) [Fase 2]

## Criação da Variável Alvo (Y)

In [ ]:
df['target'] = (df['close'] > df['open']).astype(int)

## Criação de Preditores (X) baseados em Lags

In [ ]:
df['variation'] = (df['close'] - df['open']) / df['open']
df['prev_variation'] = df['variation'].shift(1)
df['prev_variation_2'] = df['variation'].shift(2)
df['prev_variation_3'] = df['variation'].shift(3)
df['volume_log'] = np.log1p(df['volume'])

df['prev_volume'] = df['volume_log'].shift(1)
df['prev_volume_2'] = df['volume_log'].shift(2)

df_final = df[['prev_variation', 'prev_variation_2', 'prev_variation_3', 'prev_volume', 'prev_volume_2', 'target']].dropna()

print("Colunas extras removidas e valores nulos excluídos.")
df_final.head()

Colunas extras removidas e valores nulos excluídos.

,prev_variation,prev_variation_2,prev_variation_3,prev_volume,prev_volume_2,target
2026-01-29,-0.000034,-0.011105,0.010813,15.571703,14.895525,0
2026-01-30,-0.027119,-0.000034,-0.011105,16.130511,15.571703,0
2026-02-02,-0.002926,-0.027119,-0.000034,15.597332,16.130511,1
2026-02-03,0.023479,-0.002926,-0.027119,15.337469,15.597332,0
2026-02-04,-0.057907,0.023479,-0.002926,16.239961,15.337469,0

# Pipeline 3 | Tratamento e Normalização [Fase 3]

In [ ]:
df_final.head()

,prev_variation,prev_variation_2,prev_variation_3,prev_volume,prev_volume_2,target
2026-01-29,-0.000034,-0.011105,0.010813,15.571703,14.895525,0
2026-01-30,-0.027119,-0.000034,-0.011105,16.130511,15.571703,0
2026-02-02,-0.002926,-0.027119,-0.000034,15.597332,16.130511,1
2026-02-03,0.023479,-0.002926,-0.027119,15.337469,15.597332,0
2026-02-04,-0.057907,0.023479,-0.002926,16.239961,15.337469,0

## Verificação de valores nulos

In [ ]:
df_final.isnull().sum()

prev_variation      0
prev_variation_2    0
prev_variation_3    0
prev_volume         0
prev_volume_2       0
target              0
dtype: int64

## Estatísticas descritivas

In [ ]:
df_final.describe()

,prev_variation,prev_variation_2,prev_variation_3,prev_volume,prev_volume_2,target
count,97.000000,97.000000,97.000000,97.000000,97.000000,97.000000
mean,-0.001980,-0.002092,-0.001856,15.697479,15.692192,0.474227
std,0.025717,0.025733,0.025745,0.499245,0.505020,0.501929
min,-0.121948,-0.121948,-0.121948,14.672507,14.672507,0.000000
25%,-0.012082,-0.012082,-0.011105,15.387766,15.378166,0.000000
50%,-0.001019,-0.002313,-0.001019,15.585256,15.585256,0.000000
75%,0.009595,0.009595,0.010526,15.939114,15.939114,1.000000
max,0.087669,0.087669,0.087669,17.308381,17.308381,1.000000

## Remoção de Outliers

In [ ]:
df_final = df_final[
    (np.abs(df_final['prev_variation']) < 3 * df_final['prev_variation'].std()) &
    (np.abs(df_final['prev_variation_2']) < 3 * df_final['prev_variation_2'].std()) &
    (np.abs(df_final['prev_variation_3']) < 3 * df_final['prev_variation_3'].std())
]

## Seleção de Variáveis (X e y)

In [ ]:
X = df_final[['prev_variation', 'prev_variation_2', 'prev_variation_3', 'prev_volume', 'prev_volume_2']]
y = df_final['target']

## Análise de Balanceamento das Classes

In [ ]:
print(y.value_counts())

target
0    49
1    42
Name: count, dtype: int64

## Divisão Treino/Teste

In [ ]:
tamanho = int(len(X)*0.9)

X_train = X[:tamanho]
X_test = X[tamanho:]

y_train = y[:tamanho]
y_test = y[tamanho:]

## Normalização (StandardScaler)

In [ ]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Pipeline 4 | Decision Tree [Fase 4]

In [ ]:
arvore_ibm = DecisionTreeClassifier(criterion='entropy', random_state=0)
arvore_ibm.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [ ]:
previsoes_arvore = arvore_ibm.predict(X_test)

In [ ]:
previsoes_arvore

array([1, 0, 0, 0, 1, 0, 0, 1, 1, 0])

In [ ]:
accuracy_score(y_test, previsoes_arvore)

0.5

In [ ]:
confusion_matrix(y_test, previsoes_arvore)

array([[5, 4],
       [1, 0]])

In [ ]:
print(classification_report(y_test, previsoes_arvore))

              precision    recall  f1-score   support

           0       0.83      0.56      0.67         9
           1       0.00      0.00      0.00         1

    accuracy                           0.50        10
   macro avg       0.42      0.28      0.33        10
weighted avg       0.75      0.50      0.60        10

## Avaliação do modelo

In [ ]:
print(classification_report(y_test, y_pred_arvore))

              precision    recall  f1-score   support

           0       1.00      0.22      0.36         9
           1       0.12      1.00      0.22         1

    accuracy                           0.30        10
   macro avg       0.56      0.61      0.29        10
weighted avg       0.91      0.30      0.35        10

# Pipeline 5 | Modelagem por Random Forest [Fase 5]

In [ ]:
random_ibm = RandomForestClassifier(n_estimators=10, criterion='entropy', random_state=0)
random_ibm.fit(X_train, y_train)
random_ibm

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [ ]:
previsoes_random = random_ibm.predict(X_test)

In [ ]:
previsoes_random

array([1, 0, 1, 0, 1, 1, 0, 1, 0, 1])

In [ ]:
accuracy_score(y_test, previsoes_random)

0.5

In [ ]:
confusion_matrix(y_test, previsoes_random)

array([[4, 5],
       [0, 1]])

In [ ]:
print(classification_report(y_test, previsoes_random))

              precision    recall  f1-score   support

           0       1.00      0.44      0.62         9
           1       0.17      1.00      0.29         1

    accuracy                           0.50        10
   macro avg       0.58      0.72      0.45        10
weighted avg       0.92      0.50      0.58        10

# Pipeline 6 | SVM [Fase 6]

In [ ]:
svm_ibm = SVC(kernel='rbf', C=2.0, random_state=1)
svm_ibm.fit(X_train, y_train)
svm_ibm

SVC(C=2.0, random_state=1)

In [ ]:
svm_previsoes = svm_ibm.predict(X_test)
svm_previsoes

array([0, 1, 1, 1, 1, 1, 1, 1, 0, 1])

In [ ]:
accuracy_score(y_test, svm_previsoes)

0.3

In [ ]:
confusion_matrix(y_test, svm_previsoes)

array([[2, 7],
       [0, 1]])

In [ ]:
print(classification_report(y_test, svm_previsoes))

              precision    recall  f1-score   support

           0       1.00      0.22      0.36         9
           1       0.12      1.00      0.22         1

    accuracy                           0.30        10
   macro avg       0.56      0.61      0.29        10
weighted avg       0.91      0.30      0.35        10

## Armazenamento de métricas

In [ ]:
acc_svm = accuracy_score(y_test, y_pred_svm)
prec_svm = precision_score(y_test, y_pred_svm)
rec_svm = recall_score(y_test, y_pred_svm)
f1_svm = f1_score(y_test, y_pred_svm)

# Pipeline 7 | Redes Neurais [Fase 7 - IBM Base]

In [ ]:
redeneural_ibm = MLPClassifier(verbose=True, max_iter=1000, tol=0.000010, solver='adam', hidden_layer_sizes=(100), activation='relu')
redeneural_ibm.fit(X_train, y_train)
redeneural_ibm

Iteration 1, loss = 0.68084209
Iteration 2, loss = 0.67783545
Iteration 3, loss = 0.67497082
Iteration 4, loss = 0.67222120
Iteration 5, loss = 0.66956566
Iteration 6, loss = 0.66702342
Iteration 7, loss = 0.66458806
Iteration 8, loss = 0.66223747
Iteration 9, loss = 0.65998676
Iteration 10, loss = 0.65781204
Iteration 11, loss = 0.65569213
Iteration 12, loss = 0.65362819
Iteration 13, loss = 0.65162656
Iteration 14, loss = 0.64967066
Iteration 15, loss = 0.64777506
Iteration 16, loss = 0.64594817
Iteration 17, loss = 0.64415696
Iteration 18, loss = 0.64240527
Iteration 19, loss = 0.64068544
Iteration 20, loss = 0.63898553
Iteration 21, loss = 0.63730407
Iteration 22, loss = 0.63563171
Iteration 23, loss = 0.63400299
Iteration 24, loss = 0.63240361
Iteration 25, loss = 0.63081955
Iteration 26, loss = 0.62926992
Iteration 27, loss = 0.62773315
Iteration 28, loss = 0.62621165
Iteration 29, loss = 0.62469931
Iteration 30, loss = 0.62320829
Iteration 31, loss = 0.62172109
Iteration 32, loss = 0.62024705
Iteration 33, loss = 0.61880061
Iteration 34, loss = 0.61736602
Iteration 35, loss = 0.61593933
Iteration 36, loss = 0.61452348
Iteration 37, loss = 0.61313387
Iteration 38, loss = 0.61175348
Iteration 39, loss = 0.61037598
Iteration 40, loss = 0.60900705
Iteration 41, loss = 0.60764255
Iteration 42, loss = 0.60628296
Iteration 43, loss = 0.60493276
Iteration 44, loss = 0.60360443
Iteration 45, loss = 0.60230047
Iteration 46, loss = 0.60101155
Iteration 47, loss = 0.59974648
Iteration 48, loss = 0.59849129
Iteration 49, loss = 0.59724778
Iteration 50, loss = 0.59601418
Iteration 51, loss = 0.59478798
Iteration 52, loss = 0.59357957
Iteration 53, loss = 0.59238807
Iteration 54, loss = 0.59120179
Iteration 55, loss = 0.59002552
Iteration 56, loss = 0.58885608
Iteration 57, loss = 0.58769701
Iteration 58, loss = 0.58654958
Iteration 59, loss = 0.58540653
Iteration 60, loss = 0.58427550
Iteration 61, loss = 0.58315459
Iteration 62, loss = 0.58203591
Iteration 63, loss = 0.58091811
Iteration 64, loss = 0.57980659
Iteration 65, loss = 0.57869543
Iteration 66, loss = 0.57758884
Iteration 67, loss = 0.57649457
Iteration 68, loss = 0.57541860
Iteration 69, loss = 0.57435649
Iteration 70, loss = 0.57330555
Iteration 71, loss = 0.57225988
Iteration 72, loss = 0.57121694
Iteration 73, loss = 0.57019376
Iteration 74, loss = 0.56918067
Iteration 75, loss = 0.56817312
Iteration 76, loss = 0.56716283
Iteration 77, loss = 0.56615606
Iteration 78, loss = 0.56516290
Iteration 79, loss = 0.56417356
Iteration 80, loss = 0.56319566
Iteration 81, loss = 0.56220884
Iteration 82, loss = 0.56121830
Iteration 83, loss = 0.56022628
Iteration 84, loss = 0.55924794
Iteration 85, loss = 0.55827427
Iteration 86, loss = 0.55730504
Iteration 87, loss = 0.55634611
Iteration 88, loss = 0.55540509
Iteration 89, loss = 0.55447532
Iteration 90, loss = 0.55353586
Iteration 91, loss = 0.55261576
Iteration 92, loss = 0.55171310
Iteration 93, loss = 0.55081348
Iteration 94, loss = 0.54992044
Iteration 95, loss = 0.54903864
Iteration 96, loss = 0.54816413
Iteration 97, loss = 0.54729739
Iteration 98, loss = 0.54644108
Iteration 99, loss = 0.54559674
Iteration 100, loss = 0.54475807
Iteration 101, loss = 0.54393213
Iteration 102, loss = 0.54311951
Iteration 103, loss = 0.54230990
Iteration 104, loss = 0.54150825
Iteration 105, loss = 0.54071198
Iteration 106, loss = 0.53992087
Iteration 107, loss = 0.53913729
Iteration 108, loss = 0.53835211
Iteration 109, loss = 0.53757560
Iteration 110, loss = 0.53680565
Iteration 111, loss = 0.53603501
Iteration 112, loss = 0.53526715
Iteration 113, loss = 0.53448754
Iteration 114, loss = 0.53370421
Iteration 115, loss = 0.53293812
Iteration 116, loss = 0.53217824
Iteration 117, loss = 0.53141972
Iteration 118, loss = 0.53065169
Iteration 119, loss = 0.52988603
Iteration 120, loss = 0.52912235
Iteration 121, loss = 0.52836085
Iteration 122, loss = 0.52759855
Iteration 123, loss = 0.52682561
Iteration 124, loss = 0.52604976
Iteration 125, loss = 0.52527713
Iteration 126, loss = 0.52450463
Iteration 127, loss = 0.52373697
Iteration 128, loss = 0.52297526
Iteration 129, loss = 0.52221355
Iteration 130, loss = 0.52144647
Iteration 131, loss = 0.52067885
Iteration 132, loss = 0.51990405
Iteration 133, loss = 0.51913245
Iteration 134, loss = 0.51836321
Iteration 135, loss = 0.51758567
Iteration 136, loss = 0.51681494
Iteration 137, loss = 0.51605640
Iteration 138, loss = 0.51529960
Iteration 139, loss = 0.51454580
Iteration 140, loss = 0.51379689
Iteration 141, loss = 0.51305895
Iteration 142, loss = 0.51231853
Iteration 143, loss = 0.51157522
Iteration 144, loss = 0.51083698
Iteration 145, loss = 0.51009944
Iteration 146, loss = 0.50936081
Iteration 147, loss = 0.50862865
Iteration 148, loss = 0.50790014
Iteration 149, loss = 0.50718524
Iteration 150, loss = 0.50647255
Iteration 151, loss = 0.50575476
Iteration 152, loss = 0.50503964
Iteration 153, loss = 0.50433195
Iteration 154, loss = 0.50362614
Iteration 155, loss = 0.50291445
Iteration 156, loss = 0.50220962
Iteration 157, loss = 0.50150922
Iteration 158, loss = 0.50081786
Iteration 159, loss = 0.50012296
Iteration 160, loss = 0.49942376
Iteration 161, loss = 0.49873009
Iteration 162, loss = 0.49803739
Iteration 163, loss = 0.49735740
Iteration 164, loss = 0.49667689
Iteration 165, loss = 0.49599604
Iteration 166, loss = 0.49531218
Iteration 167, loss = 0.49463876
Iteration 168, loss = 0.49396306
Iteration 169, loss = 0.49329363
Iteration 170, loss = 0.49262241
Iteration 171, loss = 0.49193993
Iteration 172, loss = 0.49125589
Iteration 173, loss = 0.49058590
Iteration 174, loss = 0.48992768
Iteration 175, loss = 0.48927154
Iteration 176, loss = 0.48861312
Iteration 177, loss = 0.48795677
Iteration 178, loss = 0.48730384
Iteration 179, loss = 0.48665116
Iteration 180, loss = 0.48600221
Iteration 181, loss = 0.48536202
Iteration 182, loss = 0.48472547
Iteration 183, loss = 0.48409174
Iteration 184, loss = 0.48346897
Iteration 185, loss = 0.48284302
Iteration 186, loss = 0.48220906
Iteration 187, loss = 0.48157929
Iteration 188, loss = 0.48095396
Iteration 189, loss = 0.48032032
Iteration 190, loss = 0.47969294
Iteration 191, loss = 0.47906882
Iteration 192, loss = 0.47844670
Iteration 193, loss = 0.47783212
Iteration 194, loss = 0.47721746
Iteration 195, loss = 0.47659124
Iteration 196, loss = 0.47596869
Iteration 197, loss = 0.47534755
Iteration 198, loss = 0.47472932
Iteration 199, loss = 0.47411417
Iteration 200, loss = 0.47350872
Iteration 201, loss = 0.47289593
Iteration 202, loss = 0.47227794
Iteration 203, loss = 0.47165714
Iteration 204, loss = 0.47104349
Iteration 205, loss = 0.47043407
Iteration 206, loss = 0.46982547
Iteration 207, loss = 0.46920929
Iteration 208, loss = 0.46858549
Iteration 209, loss = 0.46796270
Iteration 210, loss = 0.46733789
Iteration 211, loss = 0.46671442
Iteration 212, loss = 0.46611327
Iteration 213, loss = 0.46550894
Iteration 214, loss = 0.46489756
Iteration 215, loss = 0.46428786
Iteration 216, loss = 0.46368729
Iteration 217, loss = 0.46308580
Iteration 218, loss = 0.46248026
Iteration 219, loss = 0.46186999
Iteration 220, loss = 0.46126346
Iteration 221, loss = 0.46065717
Iteration 222, loss = 0.46004512
Iteration 223, loss = 0.45944065
Iteration 224, loss = 0.45883686
Iteration 225, loss = 0.45822161
Iteration 226, loss = 0.45760358
Iteration 227, loss = 0.45699104
Iteration 228, loss = 0.45637578
Iteration 229, loss = 0.45575946
Iteration 230, loss = 0.45513452
Iteration 231, loss = 0.45451991
Iteration 232, loss = 0.45389919
Iteration 233, loss = 0.45327813
Iteration 234, loss = 0.45266345
Iteration 235, loss = 0.45204969
Iteration 236, loss = 0.45144666
Iteration 237, loss = 0.45084042
Iteration 238, loss = 0.45022873
Iteration 239, loss = 0.44961819
Iteration 240, loss = 0.44900745
Iteration 241, loss = 0.44839627
Iteration 242, loss = 0.44777960
Iteration 243, loss = 0.44716980
Iteration 244, loss = 0.44656335
Iteration 245, loss = 0.44596370
Iteration 246, loss = 0.44536279
Iteration 247, loss = 0.44477168
Iteration 248, loss = 0.44417184
Iteration 249, loss = 0.44357079
Iteration 250, loss = 0.44297411
Iteration 251, loss = 0.44237883
Iteration 252, loss = 0.44178306
Iteration 253, loss = 0.44119841
Iteration 254, loss = 0.44061354
Iteration 255, loss = 0.44003183
Iteration 256, loss = 0.43945277
Iteration 257, loss = 0.43886324
Iteration 258, loss = 0.43828587
Iteration 259, loss = 0.43769970
Iteration 260, loss = 0.43710747
Iteration 261, loss = 0.43651276
Iteration 262, loss = 0.43593449
Iteration 263, loss = 0.43535343
Iteration 264, loss = 0.43476908
Iteration 265, loss = 0.43418918
Iteration 266, loss = 0.43360213
Iteration 267, loss = 0.43301457
Iteration 268, loss = 0.43243463
Iteration 269, loss = 0.43185208
Iteration 270, loss = 0.43126062
Iteration 271, loss = 0.43067232
Iteration 272, loss = 0.43007993
Iteration 273, loss = 0.42948300
Iteration 274, loss = 0.42888454
Iteration 275, loss = 0.42829289
Iteration 276, loss = 0.42770692
Iteration 277, loss = 0.42711292
Iteration 278, loss = 0.42652262
Iteration 279, loss = 0.42593551
Iteration 280, loss = 0.42534912
Iteration 281, loss = 0.42475222
Iteration 282, loss = 0.42416012
Iteration 283, loss = 0.42358245
Iteration 284, loss = 0.42299113
Iteration 285, loss = 0.42240050
Iteration 286, loss = 0.42180869
Iteration 287, loss = 0.42121608
Iteration 288, loss = 0.42062673
Iteration 289, loss = 0.42002901
Iteration 290, loss = 0.41942663
Iteration 291, loss = 0.41883186
Iteration 292, loss = 0.41825548
Iteration 293, loss = 0.41767252
Iteration 294, loss = 0.41708566
Iteration 295, loss = 0.41650580
Iteration 296, loss = 0.41592752
Iteration 297, loss = 0.41534000
Iteration 298, loss = 0.41474607
Iteration 299, loss = 0.41415027
Iteration 300, loss = 0.41356277
Iteration 301, loss = 0.41296669
Iteration 302, loss = 0.41236890
Iteration 303, loss = 0.41176621
Iteration 304, loss = 0.41114562
Iteration 305, loss = 0.41052676
Iteration 306, loss = 0.40991732
Iteration 307, loss = 0.40930756
Iteration 308, loss = 0.40869965
Iteration 309, loss = 0.40810799
Iteration 310, loss = 0.40751492
Iteration 311, loss = 0.40691333
Iteration 312, loss = 0.40631328
Iteration 313, loss = 0.40571069
Iteration 314, loss = 0.40512448
Iteration 315, loss = 0.40452426
Iteration 316, loss = 0.40391508
Iteration 317, loss = 0.40331956
Iteration 318, loss = 0.40272674
Iteration 319, loss = 0.40213264
Iteration 320, loss = 0.40153682
Iteration 321, loss = 0.40094473
Iteration 322, loss = 0.40036133
Iteration 323, loss = 0.39977193
Iteration 324, loss = 0.39918213
Iteration 325, loss = 0.39860495
Iteration 326, loss = 0.39803553
Iteration 327, loss = 0.39747627
Iteration 328, loss = 0.39690015
Iteration 329, loss = 0.39631620
Iteration 330, loss = 0.39572984
Iteration 331, loss = 0.39515497
Iteration 332, loss = 0.39457289
Iteration 333, loss = 0.39398186
Iteration 334, loss = 0.39340205
Iteration 335, loss = 0.39282300
Iteration 336, loss = 0.39223843
Iteration 337, loss = 0.39164529
Iteration 338, loss = 0.39105077
Iteration 339, loss = 0.39045733
Iteration 340, loss = 0.38986311
Iteration 341, loss = 0.38925550
Iteration 342, loss = 0.38867026
Iteration 343, loss = 0.38808905
Iteration 344, loss = 0.38748881
Iteration 345, loss = 0.38689390
Iteration 346, loss = 0.38631068
Iteration 347, loss = 0.38573176
Iteration 348, loss = 0.38514951
Iteration 349, loss = 0.38456899
Iteration 350, loss = 0.38399279
Iteration 351, loss = 0.38341758
Iteration 352, loss = 0.38284941
Iteration 353, loss = 0.38227966
Iteration 354, loss = 0.38171417
Iteration 355, loss = 0.38115018
Iteration 356, loss = 0.38056944
Iteration 357, loss = 0.38000626
Iteration 358, loss = 0.37945567
Iteration 359, loss = 0.37889704
Iteration 360, loss = 0.37832995
Iteration 361, loss = 0.37776698
Iteration 362, loss = 0.37721592
Iteration 363, loss = 0.37666204
Iteration 364, loss = 0.37610556
Iteration 365, loss = 0.37554991
Iteration 366, loss = 0.37498792
Iteration 367, loss = 0.37442848
Iteration 368, loss = 0.37386519
Iteration 369, loss = 0.37331493
Iteration 370, loss = 0.37276611
Iteration 371, loss = 0.37221805
Iteration 372, loss = 0.37165934
Iteration 373, loss = 0.37110979
Iteration 374, loss = 0.37055579
Iteration 375, loss = 0.36999805
Iteration 376, loss = 0.36944735
Iteration 377, loss = 0.36889801
Iteration 378, loss = 0.36836191
Iteration 379, loss = 0.36781237
Iteration 380, loss = 0.36727088
Iteration 381, loss = 0.36673243
Iteration 382, loss = 0.36618308
Iteration 383, loss = 0.36564117
Iteration 384, loss = 0.36510795
Iteration 385, loss = 0.36456900
Iteration 386, loss = 0.36403975
Iteration 387, loss = 0.36349547
Iteration 388, loss = 0.36294984
Iteration 389, loss = 0.36240438
Iteration 390, loss = 0.36187226
Iteration 391, loss = 0.36133342
Iteration 392, loss = 0.36079811
Iteration 393, loss = 0.36026260
Iteration 394, loss = 0.35973759
Iteration 395, loss = 0.35919795
Iteration 396, loss = 0.35866233
Iteration 397, loss = 0.35812847
Iteration 398, loss = 0.35759538
Iteration 399, loss = 0.35706026
Iteration 400, loss = 0.35653294
Iteration 401, loss = 0.35599477
Iteration 402, loss = 0.35546352
Iteration 403, loss = 0.35492893
Iteration 404, loss = 0.35439497
Iteration 405, loss = 0.35387383
Iteration 406, loss = 0.35333934
Iteration 407, loss = 0.35281102
Iteration 408, loss = 0.35228256
Iteration 409, loss = 0.35175207
Iteration 410, loss = 0.35122331
Iteration 411, loss = 0.35069383
Iteration 412, loss = 0.35015606
Iteration 413, loss = 0.34962641
Iteration 414, loss = 0.34908495
Iteration 415, loss = 0.34855351
Iteration 416, loss = 0.34801790
Iteration 417, loss = 0.34749132
Iteration 418, loss = 0.34696949
Iteration 419, loss = 0.34644229
Iteration 420, loss = 0.34592200
Iteration 421, loss = 0.34540100
Iteration 422, loss = 0.34487761
Iteration 423, loss = 0.34433518
Iteration 424, loss = 0.34379057
Iteration 425, loss = 0.34327256
Iteration 426, loss = 0.34274406
Iteration 427, loss = 0.34221897
Iteration 428, loss = 0.34169822
Iteration 429, loss = 0.34118461
Iteration 430, loss = 0.34067595
Iteration 431, loss = 0.34015223
Iteration 432, loss = 0.33962739
Iteration 433, loss = 0.33910197
Iteration 434, loss = 0.33857793
Iteration 435, loss = 0.33804718
Iteration 436, loss = 0.33753150
Iteration 437, loss = 0.33701786
Iteration 438, loss = 0.33649621
Iteration 439, loss = 0.33598082
Iteration 440, loss = 0.33546582
Iteration 441, loss = 0.33495610
Iteration 442, loss = 0.33442886
Iteration 443, loss = 0.33390033
Iteration 444, loss = 0.33338757
Iteration 445, loss = 0.33286685
Iteration 446, loss = 0.33234117
Iteration 447, loss = 0.33183489
Iteration 448, loss = 0.33131786
Iteration 449, loss = 0.33079336
Iteration 450, loss = 0.33027187
Iteration 451, loss = 0.32975084
Iteration 452, loss = 0.32921923
Iteration 453, loss = 0.32871124
Iteration 454, loss = 0.32819912
Iteration 455, loss = 0.32768189
Iteration 456, loss = 0.32717203
Iteration 457, loss = 0.32666880
Iteration 458, loss = 0.32616858
Iteration 459, loss = 0.32567553
Iteration 460, loss = 0.32518114
Iteration 461, loss = 0.32468544
Iteration 462, loss = 0.32417815
Iteration 463, loss = 0.32368788
Iteration 464, loss = 0.32319215
Iteration 465, loss = 0.32268945
Iteration 466, loss = 0.32219226
Iteration 467, loss = 0.32170220
Iteration 468, loss = 0.32121500
Iteration 469, loss = 0.32073048
Iteration 470, loss = 0.32024334
Iteration 471, loss = 0.31975749
Iteration 472, loss = 0.31926613
Iteration 473, loss = 0.31877344
Iteration 474, loss = 0.31828662
Iteration 475, loss = 0.31779442
Iteration 476, loss = 0.31730562
Iteration 477, loss = 0.31681777
Iteration 478, loss = 0.31631517
Iteration 479, loss = 0.31581131
Iteration 480, loss = 0.31531097
Iteration 481, loss = 0.31480570
Iteration 482, loss = 0.31431889
Iteration 483, loss = 0.31382772
Iteration 484, loss = 0.31334723
Iteration 485, loss = 0.31285418
Iteration 486, loss = 0.31237134
Iteration 487, loss = 0.31188431
Iteration 488, loss = 0.31141647
Iteration 489, loss = 0.31094309
Iteration 490, loss = 0.31046176
Iteration 491, loss = 0.30997558
Iteration 492, loss = 0.30949230
Iteration 493, loss = 0.30901341
Iteration 494, loss = 0.30853277
Iteration 495, loss = 0.30805150
Iteration 496, loss = 0.30757152
Iteration 497, loss = 0.30708674
Iteration 498, loss = 0.30662022
Iteration 499, loss = 0.30614173
Iteration 500, loss = 0.30566109
Iteration 501, loss = 0.30519364
Iteration 502, loss = 0.30473115
Iteration 503, loss = 0.30427598
Iteration 504, loss = 0.30379694
Iteration 505, loss = 0.30331793
Iteration 506, loss = 0.30284451
Iteration 507, loss = 0.30237328
Iteration 508, loss = 0.30190311
Iteration 509, loss = 0.30143258
Iteration 510, loss = 0.30096866
Iteration 511, loss = 0.30050785
Iteration 512, loss = 0.30004671
Iteration 513, loss = 0.29957764
Iteration 514, loss = 0.29911277
Iteration 515, loss = 0.29865304
Iteration 516, loss = 0.29819878
Iteration 517, loss = 0.29772770
Iteration 518, loss = 0.29724858
Iteration 519, loss = 0.29677823
Iteration 520, loss = 0.29630298
Iteration 521, loss = 0.29583603
Iteration 522, loss = 0.29537199
Iteration 523, loss = 0.29490763
Iteration 524, loss = 0.29443194
Iteration 525, loss = 0.29395181
Iteration 526, loss = 0.29348160
Iteration 527, loss = 0.29300038
Iteration 528, loss = 0.29252260
Iteration 529, loss = 0.29206024
Iteration 530, loss = 0.29158628
Iteration 531, loss = 0.29110936
Iteration 532, loss = 0.29064917
Iteration 533, loss = 0.29018266
Iteration 534, loss = 0.28971746
Iteration 535, loss = 0.28924655
Iteration 536, loss = 0.28878563
Iteration 537, loss = 0.28831738
Iteration 538, loss = 0.28785400
Iteration 539, loss = 0.28739467
Iteration 540, loss = 0.28692914
Iteration 541, loss = 0.28645462
Iteration 542, loss = 0.28598136
Iteration 543, loss = 0.28551667
Iteration 544, loss = 0.28504260
Iteration 545, loss = 0.28457133
Iteration 546, loss = 0.28410081
Iteration 547, loss = 0.28362382
Iteration 548, loss = 0.28314523
Iteration 549, loss = 0.28267337
Iteration 550, loss = 0.28219784
Iteration 551, loss = 0.28171788
Iteration 552, loss = 0.28124197
Iteration 553, loss = 0.28077303
Iteration 554, loss = 0.28029270
Iteration 555, loss = 0.27980926
Iteration 556, loss = 0.27933469
Iteration 557, loss = 0.27885269
Iteration 558, loss = 0.27836943
Iteration 559, loss = 0.27789642
Iteration 560, loss = 0.27741712
Iteration 561, loss = 0.27692518
Iteration 562, loss = 0.27643996
Iteration 563, loss = 0.27595926
Iteration 564, loss = 0.27548381
Iteration 565, loss = 0.27500312
Iteration 566, loss = 0.27452313
Iteration 567, loss = 0.27404938
Iteration 568, loss = 0.27357473
Iteration 569, loss = 0.27310404
Iteration 570, loss = 0.27262748
Iteration 571, loss = 0.27215651
Iteration 572, loss = 0.27168227
Iteration 573, loss = 0.27121026
Iteration 574, loss = 0.27073802
Iteration 575, loss = 0.27026936
Iteration 576, loss = 0.26979579
Iteration 577, loss = 0.26932971
Iteration 578, loss = 0.26886318
Iteration 579, loss = 0.26838542
Iteration 580, loss = 0.26791126
Iteration 581, loss = 0.26744542
Iteration 582, loss = 0.26698557
Iteration 583, loss = 0.26650711
Iteration 584, loss = 0.26606221
Iteration 585, loss = 0.26561146
Iteration 586, loss = 0.26515073
Iteration 587, loss = 0.26468796
Iteration 588, loss = 0.26422528
Iteration 589, loss = 0.26376303
Iteration 590, loss = 0.26330122
Iteration 591, loss = 0.26283531
Iteration 592, loss = 0.26237101
Iteration 593, loss = 0.26190616
Iteration 594, loss = 0.26145232
Iteration 595, loss = 0.26098990
Iteration 596, loss = 0.26052313
Iteration 597, loss = 0.26006415
Iteration 598, loss = 0.25960013
Iteration 599, loss = 0.25914050
Iteration 600, loss = 0.25868036
Iteration 601, loss = 0.25823776
Iteration 602, loss = 0.25777860
Iteration 603, loss = 0.25731203
Iteration 604, loss = 0.25684833
Iteration 605, loss = 0.25639447
Iteration 606, loss = 0.25593493
Iteration 607, loss = 0.25545680
Iteration 608, loss = 0.25499965
Iteration 609, loss = 0.25452883

/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(

MLPClassifier(hidden_layer_sizes=100, max_iter=1000, tol=1e-05, verbose=True)

In [ ]:
redeneural_ibm.out_activation_

'logistic'

In [ ]:
previsoes_redeneural = redeneural_ibm.predict(X_test)
previsoes_redeneural

array([0, 0, 1, 1, 1, 1, 0, 0, 0, 1])

In [ ]:
accuracy_score(y_test, previsoes_redeneural)

0.6

In [ ]:
confusion_matrix(y_test, previsoes_redeneural)

array([[5, 4],
       [0, 1]])

In [ ]:
print(classification_report(y_test, previsoes_redeneural))

              precision    recall  f1-score   support

           0       1.00      0.56      0.71         9
           1       0.20      1.00      0.33         1

    accuracy                           0.60        10
   macro avg       0.60      0.78      0.52        10
weighted avg       0.92      0.60      0.68        10

# Pipeline 8 | KNN [Fase 8 - IBM Base]

In [ ]:
parametros = {'n_neighbors': [3, 5, 10, 20], 'p': [1, 2]}

In [ ]:
grid_ibm = GridSearchCV(estimator=KNeighborsClassifier(), param_grid=parametros)
grid_ibm.fit(X_train, y_train)

GridSearchCV(estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': [3, 5, 10, 20], 'p': [1, 2]})

In [ ]:
melhor_parametros_ibm = grid_ibm.best_params_
melhor_resultado_ibm = grid_ibm.best_score_

In [ ]:
print(melhor_parametros_ibm)
print(melhor_resultado_ibm)

{'n_neighbors': 20, 'p': 1}
0.5426470588235295

In [ ]:
knn_ibm = KNeighborsClassifier(n_neighbors=melhor_parametros_ibm['n_neighbors'], p=melhor_parametros_ibm['p'])
knn_ibm.fit(X_train, y_train)
knn_ibm

KNeighborsClassifier(n_neighbors=20, p=1)

In [ ]:
previsoes_knn = knn_ibm.predict(X_test)

In [ ]:
previsoes_knn

array([1, 0, 1, 1, 1, 1, 1, 0, 0, 1])

In [ ]:
accuracy_score(y_test, previsoes_knn)

0.4

In [ ]:
confusion_matrix(y_test, previsoes_knn)

array([[3, 6],
       [0, 1]])

In [ ]:
confusion_matrix(y_test, previsoes_knn)

array([[3, 6],
       [0, 1]])

In [ ]:
print(classification_report(y_test, previsoes_knn))

              precision    recall  f1-score   support

           0       1.00      0.33      0.50         9
           1       0.14      1.00      0.25         1

    accuracy                           0.40        10
   macro avg       0.57      0.67      0.38        10
weighted avg       0.91      0.40      0.47        10

# Pipeline 9 | Comparação dos modelos [Fase 9]

In [ ]:
resultado_modelos = pd.DataFrame({
    'Modelo': ['Decision Tree', 'Random Forest', 'SVM', 'Redes Neurais', 'KNN'],
    'Acurácia': [
        accuracy_score(y_test, previsoes_arvore),
        accuracy_score(y_test, previsoes_random),
        accuracy_score(y_test, svm_previsoes),
        accuracy_score(y_test, previsoes_redeneural),
        accuracy_score(y_test, previsoes_knn)
    ]
})

resultado_modelos.sort_values(by='Acurácia', ascending=False)

          Modelo  Acurácia
3  Redes Neurais       0.6
0  Decision Tree       0.5
1  Random Forest       0.5
4            KNN       0.4
2            SVM       0.3